version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /home/varun/keycloak_volumes/pgdata:/var/lib/postgresql/data
    networks:
      - keycloak-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    hostname: keycloak  # Explicitly set container hostname
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Database configuration
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      
      # Admin credentials
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      
      # Hostname configuration (now using consistent 'keycloak' hostname)
      KC_HOSTNAME: keycloak
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      
      # HTTP configuration
      KC_PROXY: edge
      KC_HTTP_ENABLED: "true"
      
      # Disable features not needed in dev
      KC_METRICS_ENABLED: "false"
    ports:
      - "8080:8080"
    command: 
      - start-dev
      - --hostname=keycloak
      - --hostname-strict=false
      - --http-enabled=true
    volumes:
      - /home/varun/keycloak_volumes/keycloak_data:/opt/keycloak/data
    networks:
      - keycloak-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  keycloak_data:

networks:
  keycloak-net:
    external: true